export const API = {
    server_url: "http://localhost:5002/media", //"/serve/media", //"http://localhost:5002/media",
    server_api_url: "http://localhost:5002/api", //"/serve/api", //"http://localhost:5002/api",
    ipfs_url: "https://ipfs.io/ipfs/",
    cookie_expire: 60,  //1h
    user_login: "/user/login",
    user_opt_verify: "/user/opt_verify",
    user_profile_image: "/images/user/",
    user_profile_image_upload: '/media/avatar',
    user_update: "/user/update",
    user_getUser: "/user/getUserDetail",
    user_getUserById: "/user/getUserDetailById",

    collection_add: "/collection/add",
    collection_update: "/collection/update",
    collection_detail: "/collection/detail",
    collection_delete: "/collection/delete",    
    collection_list: "/collection/list",    
    collection_bannerImage: "/images/collection/banner/",
    collection_bannerImage_upload: '/media/collectionbanner',
    collection_featuredImage: "/images/collection/featured/",
    collection_featuredImage_upload: '/media/collectionfeatured',
    collection_logoImage: "/images/collection/logo/",
    collection_logoImage_upload: '/media/collectionlogo',
    collection_getCollection: '/collection/getCollection',

    getTokenMaxSlot: "/item/getMaxSlot",
    slot_add: "/item/slotAdd",
    item_add: "/item/add",
    item_list: "/item/list",
    item_lazylist: "/item/lazyitems",
    item_getItem: "/item/getItem",
    item_media_upload: "/media/itemmedia",
    item_media: "/item/media/",
    uploadMetadata: "/item/uploadMetadata",
    uploadSlotData: "/item/uploadSlotData",
    getItemMetadata: "/item/getItemMetadata",
    getSlotMetadata: "/item/getItemSlotdata",
    getItemId: "/item/getItemId",


    item_marketList: "/item/marketListItem",
    item_getListedCollections: "/item/getListedCollections",
    item_getTopCollectionsToday: "/item/getTopCollectionsToday",
    item_getNotableCollections: "/item/getNotableCollections",
    item_getListedCollectionItem: "/item/getListedCollectionItem",
    item_getListedItems: "/item/getListedItems",
    item_getAuctionedItems: "/item/getAuctionedItems",
    item_getNewItems: "/item/getNewItems",
    item_getEarningsOnItems: "/item/getEarningsOnItems",
    item_getEarningsOffItems: "/item/getEarningsOffItems",
    item_createOrder: "/item/createOrder",
    item_addTrade: "/item/addTrade",
    item_listBuyPrices: "/item/listBuyPrices",
    item_listSellPrices: "/item/listSellPrices"
}